## Support Vector Regression Implementation

In [4]:
## dataset (Tips dataset)
import seaborn as sns
df = sns.load_dataset('tips')

In [5]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [7]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [8]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [10]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [11]:
## independent and dependent features 
X = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state=10)

In [14]:
X_train.head()

      tip   sex smoker  day    time  size
58   1.76  Male    Yes  Sat  Dinner     2
1    1.66  Male     No  Sun  Dinner     3
2    3.50  Male     No  Sun  Dinner     3
68   2.01  Male     No  Sat  Dinner     2
184  3.00  Male    Yes  Sun  Dinner     2

In [15]:
## Feature encoding (label encoding and Onehot encoding)

In [16]:
# applying label encoding for binary features 
from sklearn.preprocessing import LabelEncoder

In [17]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [18]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [19]:
X_train.head()

      tip  sex  smoker  day  time  size
58   1.76    1       1  Sat     0     2
1    1.66    1       0  Sun     0     3
2    3.50    1       0  Sun     0     3
68   2.01    1       0  Sat     0     2
184  3.00    1       1  Sun     0     2

In [20]:
X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])
X_test['time']=le3.transform(X_test['time'])

In [21]:
X_test.head()

      tip  sex  smoker  day  time  size
162  2.00    0       0  Sun     0     3
60   3.21    1       1  Sat     0     2
61   2.00    1       1  Sat     0     2
63   3.76    1       1  Sat     0     4
69   2.09    1       1  Sat     0     2

In [22]:
# Onehot encoding -- column Transformer

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [30]:
ct = ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],
                                     remainder = 'passthrough' )

In [33]:
import sys
import numpy 
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [34]:
X_test = ct.transform(X_test)

In [35]:
## SVR - Support vector Regression
from sklearn.svm import SVR
svr = SVR()

In [36]:
svr.fit(X_train,y_train)

SVR()

In [37]:
y_pred = svr.predict(X_test)

In [38]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.4602811456115927
4.1486423210190235